>Os0006#SINE#F524|SINE Os0006#SINE/unknown|F524 ID=Os0006#SINE/unknown|F524;gene=F524;clade=SINE;evalue=4.8e-99;coverage=91.3;probability=0.96
AGCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTT
CGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGTTCTCCAGGATTTGCCGGCCC
AGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGCGTTCATAGGGGTGAGTGT
GCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAAAAAAAA
>Os0006#SINE#OsSN3|SINE Os0006#SINE/unknown|OsSN3 ID=Os0006#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=3.5e-15;coverage=38.2;probability=0.88
AGCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTT
CGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTG
>Os0006#SINE#SINE2-1a_SBi|SINE Os0006#SINE/unknown|SINE2-1a_SBi ID=Os0006#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=1.2e-19;coverage=30.7;probability=0.85
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTC
GACTCCTCATGGGAGCGAATTTTCCAGGATTTAA
>Os0006#SINE#SINE2-1c_SBi|SINE Os0006#SINE/unknown|SINE2-1c_SBi ID=Os0006#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=1.3e-08;coverage=26.8;probability=0.82
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTC
GACTCCTCATGGGAGCGAATTTTCCAGGATTTAACG
>Os0006#SINE#SINE2-1_SBi|SINE Os0006#SINE/unknown|SINE2-1_SBi ID=Os0006#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.4e-10;coverage=24.5;probability=0.91
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTCGAC
TCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACG
TACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGTTCTCCAGGATTTGCCGGCCCAGTC
TTCGAAGATGCTCATAGGGGTAGGGTTT
>Os0006#SINE#AtSB4|SINE Os0006#SINE/unknown|AtSB4 ID=Os0006#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=7.4e-05;coverage=52.8;probability=0.72
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTCGAC
TCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACG
T
>Os0006#SINE#BoSB8A|SINE Os0006#SINE/unknown|BoSB8A ID=Os0006#SINE/unknown|BoSB8A;gene=BoSB8A;clade=SINE;evalue=0.00025;coverage=66.3;probability=0.76
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTCGAC
TCCTCATGGGAGCGAATTTTCCAGGATTTA
>Os0006#SINE#SINE2-12_OS|SINE Os0006#SINE/unknown|SINE2-12_OS ID=Os0006#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=5.1e-16;coverage=24.2;probability=0.89
GGGCCTGTAGCCTAGTGGTTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTCGACTCC
TCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTAC
>Os0006#SINE#CASINE|SINE Os0006#SINE/unknown|CASINE ID=Os0006#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=3.3e-05;coverage=22.3;probability=0.81
TTACAAGAGCCTCATAGCACCTGAGGTCCTGGGTTCGACTCCTCATGGGAGCGAATTTTC
CAGGATTTAACGGCGTTGTGCTTTCAGT
>Os0006#SINE#SINE2-12_SBi|SINE Os0006#SINE/unknown|SINE2-12_SBi ID=Os0006#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=1.2e-53;coverage=82.6;probability=0.87
ATAGCACCTGAGGTCCTGGGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGG
CGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTC
GTTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGC
GTGCGTTCATAGGGGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTC
TCAAAAAAAAA
>Os0006#SINE#SINE2-11_SBi|SINE Os0006#SINE/unknown|SINE2-11_SBi ID=Os0006#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=1.1e-20;coverage=80.7;probability=0.71
ATAGCACCTGAGGTCCTGGGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGG
CGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTC
GTTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGC
GTGCGTTCATAGGGGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTC
TCAAAAAAAAA
>Os0006#SINE#SINE2-1_BDi|SINE Os0006#SINE/unknown|SINE2-1_BDi ID=Os0006#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=2.3e-44;coverage=69.6;probability=0.83
AGCACCTGAGGTCCTGGGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCG
TTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGT
TCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGT
GCGTTCATAGGGGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTC
AAAAAAAAA
>Os0006#SINE#SINE2-1_OS|SINE Os0006#SINE/unknown|SINE2-1_OS ID=Os0006#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=3.1e-06;coverage=57.3;probability=0.7
GAGGTCCTGGGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCT
TTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGTTCTCCAG
GATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGCGTTCA
TAGGGGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAAAAAA
AA
>Os0006#SINE#SINE2-2_OS|SINE Os0006#SINE/unknown|SINE2-2_OS ID=Os0006#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=9.8e-06;coverage=51.4;probability=0.58
TCCTGGGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCA
GTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGTTCTCCAGGATT
TGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGCGTTCATAGG
GGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAAAAAAA
>Os0006#SINE#SINE9_OS|SINE Os0006#SINE/unknown|SINE9_OS ID=Os0006#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=4.2e-23;coverage=32.4;probability=0.78
GGTTCGACTCCTCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGT
AGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTAACTTCGTTCTCCAGGATTTGCCG
GCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGCGTTCATAGGGGTGA
GTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAAAAAAAA
>Os0006#SINE#SINE-12_OS|SINE Os0006#SINE/unknown|SINE-12_OS ID=Os0006#SINE/unknown|SINE-12_OS;gene=SINE-12_OS;clade=SINE;evalue=2.4e-06;coverage=33.0;probability=0.6
TCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGT
GCGTTCATAGGGGTGAGTGTGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTC
AAAAAAAAA
>Os0106#SINE#p-SINE1_OS|SINE Os0106#SINE/unknown|p-SINE1_OS ID=Os0106#SINE/unknown|p-SINE1_OS;gene=p-SINE1_OS;clade=SINE;evalue=1.6e-44;coverage=76.9;probability=0.97
GAGAAACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGT
TCGAAGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTT
TTT
>Os0106#SINE#SINE1R5_OS|SINE Os0106#SINE/unknown|SINE1R5_OS ID=Os0106#SINE/unknown|SINE1R5_OS;gene=SINE1R5_OS;clade=SINE;evalue=5e-43;coverage=100.0;probability=0.99
GAGAAACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGT
TCGAAGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTT
>Os0106#SINE#SINE1_OS|SINE Os0106#SINE/unknown|SINE1_OS ID=Os0106#SINE/unknown|SINE1_OS;gene=SINE1_OS;clade=SINE;evalue=3.5e-39;coverage=100.0;probability=0.98
GAGAAACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGT
TCGAAGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTT
T
>Os0106#SINE#SINE8_OS|SINE Os0106#SINE/unknown|SINE8_OS ID=Os0106#SINE/unknown|SINE8_OS;gene=SINE8_OS;clade=SINE;evalue=3.3e-34;coverage=98.3;probability=0.98
AGAAACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTT
CGAAGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTTT
>Os0106#SINE#SINE6_OS|SINE Os0106#SINE/unknown|SINE6_OS ID=Os0106#SINE/unknown|SINE6_OS;gene=SINE6_OS;clade=SINE;evalue=2.6e-39;coverage=99.1;probability=0.98
AAACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCG
AAGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTT
>Os0106#SINE#SINE16_OS|SINE Os0106#SINE/unknown|SINE16_OS ID=Os0106#SINE/unknown|SINE16_OS;gene=SINE16_OS;clade=SINE;evalue=9e-26;coverage=85.1;probability=0.89
AACGCCCAGGGGTCTTCCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCGA
AGCCTCACCCCTTCTAATTATTTGATATTAGGTCATTCCCTAATATTCGTGTCTTTTTT
>Os0186#SINE#SINE1_SO|SINE Os0186#DNAnona/hAT|SINE1_SO ID=Os0186#DNAnona/hAT|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=0.001;coverage=31.3;probability=0.55
GTGCCTAAGTTTGTATTGAGGGGGGTGCATACATGGTGAAAATAGATAAGGTATAGCTAA
AAAAATTTCTTAACCG
>Os0217_LTR#SINE#SINE-4_Mad|SINE Os0217_LTR#LTR/Gypsy|SINE-4_Mad ID=Os0217_LTR#LTR/Gypsy|SINE-4_Mad;gene=SINE-4_Mad;clade=SINE;evalue=0.00035;coverage=52.3;probability=0.5
AGTGGTAAATTGTTGTTTTCTCTGAATTGGTGTGTGTGTGTTCAGTGGCAAAGACCACTT
TGGAATCCTTATGTACTCCTATTAAAACTATTGGCTTGTGGCCAGGAGGGAGATAAGAAA
AACCTCATTATCATTTGTTCTT
>Os0222#SINE#SINE-1_ECa|SINE Os0222#DNAnona/MULE|SINE-1_ECa ID=Os0222#DNAnona/MULE|SINE-1_ECa;gene=SINE-1_ECa;clade=SINE;evalue=8.5e-06;coverage=38.5;probability=0.44
TCCCTTCTTCCTTCTTTTTTCTCTTTTATGAAAAGACGATGACATGGACGATGATGTGTA
CGAGGCATTTTCGTCTTTTCGACAAGGAAGAAAGAGAAAAAAGAAGGAAGAAGGGAGAAA
AAAAAAAAAAAATT
>Os0248#SINE#SINE2-11_OS|SINE Os0248#LINE/unknown|SINE2-11_OS ID=Os0248#LINE/unknown|SINE2-11_OS;gene=SINE2-11_OS;clade=SINE;evalue=3.3e-29;coverage=93.5;probability=0.91
AAATGCTGAGATGCACTTTGGTAGTGCAATGGAGTGTGTGGTTTTAGTCCCGAAGTTCCA
TGTGTAATCCCAATACGCTCACAATTTCTTTTAAAAAAATGTTTGGAGGGACATCTTTCC
CTCTAAATCTCTTGTTTTTTATAAG
>Os0277#SINE#CASINE|SINE Os0277#SINE/unknown|CASINE ID=Os0277#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.7e-52;coverage=90.3;probability=0.95
CAGTGACCTGAGTAGCATCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATTTCAG
ATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTTAAATGGCTGTATATATCCGGTTGGAT
GTAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAAAAA
>Os0277#SINE#OsSN3|SINE Os0277#SINE/unknown|OsSN3 ID=Os0277#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=5.9e-51;coverage=70.0;probability=0.94
CAGTGACCTGAGTAGCATCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATTTCAG
ATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTTAAATGGCTGTATATATCCGGTTGGAT
GTAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAAAAA
>Os0277#SINE#SINE2-1_SBi|SINE Os0277#SINE/unknown|SINE2-1_SBi ID=Os0277#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.8e-14;coverage=22.7;probability=0.91
AGTGACCTGAGTAGCATCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATTTCAGA
TTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTTAAATGGC
>Os0277#SINE#SINE2-1a_SBi|SINE Os0277#SINE/unknown|SINE2-1a_SBi ID=Os0277#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=2.3e-11;coverage=23.3;probability=0.72
AGTGACCTGAGTAGCATCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATTTCAGA
TTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTTAAATGGCTGTATATATCCGGTTGGATG
TAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAAAA
>Os0343#SINE#SINE2-1a_SBi|SINE Os0343#DNAnona/CACTA|SINE2-1a_SBi ID=Os0343#DNAnona/CACTA|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=0.00023;coverage=32.7;probability=0.71
CGTAGGTGAGTTGGTAAAGGAGAGCACGCGTGAAGGATAGGTCTTGGGTTCGAATCCTAG
CCAAGACATAATATAAAAAAAATAAGT
>Os0521#SINE#SHANSINE_MT|SINE Os0521#DNAnona/hAT|SHANSINE_MT ID=Os0521#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=9.6e-06;coverage=58.7;probability=0.7
CAGGGGCGGATCCAACTTGGGACATGGGGGTTCAGTTGAACCCCCAAACTTTTGGGTGAA
CAAACAAACTGTTATTCCTTGAATTATTTAAGAGAGGTTTA
>Os0545#SINE#SHANSINE_MT|SINE Os0545#DNAnona/hAT|SHANSINE_MT ID=Os0545#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=2e-08;coverage=67.8;probability=0.78
CAGTGGCGGAGCTACGTGTAATCTGTGGGGTCAGCTGACCCCACAGGTTTTTGCAAAATA
GCCCAAAAACTATTGATATTTGCGTTGCAAC
>Os0580#SINE#F524|SINE Os0580#SINE/unknown|F524 ID=Os0580#SINE/unknown|F524;gene=F524;clade=SINE;evalue=8.2e-14;coverage=35.8;probability=0.82
AGCGAACGGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGG
GTTCGACTCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTC
>Os0580#SINE#OsSN3|SINE Os0580#SINE/unknown|OsSN3 ID=Os0580#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=6.3e-09;coverage=42.1;probability=0.88
AGCGAACGGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGG
GTTCGACTCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTCTGTC
CTACACCGAAGCACAGGT
>Os0580#SINE#SINE2-1a_SBi|SINE Os0580#SINE/unknown|SINE2-1a_SBi ID=Os0580#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=1.8e-67;coverage=99.7;probability=0.85
GCGAACGGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGG
TTCGACTCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTCTGTCC
TACACCGAAGCACAGGTCTAAGGCCTGGCCAGGTCATTGGTCGTTCTCACATGGGCTATG
GTGCTGCTGTGTAAGGTTGGGGCAGGGGTTCGGGGGTTTTCTTGACCTGCATGAGAAGGT
CTTCTTAGCAAAATACCCCGGGGTTGTCTTAACCCCCCTCAAGTCGAGTTTTTTTTA
>Os0580#SINE#SINE2-1c_SBi|SINE Os0580#SINE/unknown|SINE2-1c_SBi ID=Os0580#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=5.6e-29;coverage=93.5;probability=0.81
AACGGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGGTTC
GACTCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTCTGTCCTAC
ACCGAAGCACAGGTCTAAGGCCTGGCCAGGTCATTGGTCGTTCTCACATGGGCTATGGTG
CTGCTGTGTAAGGTTGGGGCAGGGGTTCGGGGGTTTTCTTGACCTGCATGAGAAGGTCTT
CTTAGCAAAATACCCCGGGGTTGTCTTAACCCCCCTCAAGTCGAGTTTTT
>Os0580#SINE#SINE2-1_SBi|SINE Os0580#SINE/unknown|SINE2-1_SBi ID=Os0580#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.5e-38;coverage=96.9;probability=0.79
CGGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGGTTCGA
CTCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTCTGTCCTACAC
CGAAGCACAGGTCTAAGGCCTGGCCAGGTCATTGGTCGTTCTCACATGGGCTATGGTGCT
GCTGTGTAAGGTTGGGGCAGGGGTTCGGGGGTTTTCTTGACCTGCATGAGAAGGTCTTCT
TAGCAAAATACCCCGGGGTTGTCTTAACCCCCCTCAAGTCGAGTTTTTTT
>Os0580#SINE#SINE2-12_OS|SINE Os0580#SINE/unknown|SINE2-12_OS ID=Os0580#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=1.5e-28;coverage=100.0;probability=0.72
GGGCCTCTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGGTTCGAC
TCCCCGTGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATTCCCCTCGTCTGTCCTACACC
GAAGCACAGGTCTAAGGCCTGGCCAGGTCATTGGTCGTTCTCACATGGGCTATGGTGCTG
CTGTGTAAGGTTGGGGCAGGGGTTCGGGGGTTTTCTTGACCTGCATGAGAAGGTCTTCTT
AGCAAAATACCCCGGGGTTGTCTTAACCCCCCTCAAGTCGAGTTTTTTTT
>Os0580#SINE#AtSB4|SINE Os0580#SINE/unknown|AtSB4 ID=Os0580#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=4.3e-05;coverage=24.2;probability=0.7
CTAGGTGAGTTGGTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGGTTCGACTCCCCG
TGGGAGTGAATTTCAGCTTGGGGTTAAAAAAATT
>Os0580#SINE#CASINE|SINE Os0580#SINE/unknown|CASINE ID=Os0580#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.3e-06;coverage=36.0;probability=0.87
GTTAGGTGGCTCTAGTAGCACTCCTTAGGTACTGGGTTCGACTCCCCGTGGGAGTGAATT
TCAGCTTGGGGTTAAAAAAATTCCC
>Os0604#SINE#SINE2-1_OS|SINE Os0604#SINE/unknown|SINE2-1_OS ID=Os0604#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=3.5e-06;coverage=26.2;probability=0.77
GCGCTAGTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCC
TTGTCGAGCACGCTCACCAGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACACCA
AGTCCTTCCTTGGTG
>Os0604#SINE#SINE2-3_OS|SINE Os0604#SINE/unknown|SINE2-3_OS ID=Os0604#SINE/unknown|SINE2-3_OS;gene=SINE2-3_OS;clade=SINE;evalue=6.2e-05;coverage=69.3;probability=0.72
TAGTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCTTGT
CGAGCACGCTCACCAGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACACCAAGTC
CTTCCTTGGTGTCCAACTTTTCT
>Os0604#SINE#SINE2-2_OS|SINE Os0604#SINE/unknown|SINE2-2_OS ID=Os0604#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=2e-07;coverage=27.3;probability=0.74
GTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCTTGTCG
AGCACGCTCACCAGGGAAATATTTACCTCTTCCTTCTTAAAAC
>Os0604#SINE#SINE2-4B_OS|SINE Os0604#SINE/unknown|SINE2-4B_OS ID=Os0604#SINE/unknown|SINE2-4B_OS;gene=SINE2-4B_OS;clade=SINE;evalue=6e-05;coverage=42.3;probability=0.83
CAGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACACCAAGTCCTTCCTTGGTGTC
CAACTTTTCTTTT
>Os0642#SINE#CASINE|SINE Os0642#SINE/unknown|CASINE ID=Os0642#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.8e-08;coverage=40.6;probability=0.83
TTAGTTTTATGTAAGGTGCTTGAGCCTTTGTGCTCCTTTTGTTTGTGAACTTGTGTGTAT
GAACTGAGCTTGTTCGCTCGGATTTTCTGTGGCTGTATACACCCCGTTGGTGTAGAAGCC
AGGTTTTATAAATTCCTATTATCTAAAAAAAA
>Os0642#SINE#OsSN3|SINE Os0642#SINE/unknown|OsSN3 ID=Os0642#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=0.00012;coverage=25.8;probability=0.73
TTTGTTTGTGAACTTGTGTGTATGAACTGAGCTTGTTCGCTCGGATTTTCTGTGGCTGTA
TACACCCCGTTGGTGTAGAAGCCAGGTTTTATAAATTCCTATTATCTAAAAAAAA
>Os0701#SINE#SINE1_SO|SINE Os0701#DNAnona/hAT|SINE1_SO ID=Os0701#DNAnona/hAT|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=1.4e-05;coverage=81.0;probability=0.5
CAGTGGCGGAGCCAGGAATTTAAACCTGTGGGGTCAATTACTAGTGGTTTGTATTTAAGT
GGGGTCATTTCTCTAAATTTTTTTGGATTTATACATGAAAATCAAGGTTTATAGGGTGTT
TTTTAAAAAGCTGTGGGGTCAGCCGACCCCACAGAAATGGCCTAAATCCGCCACTG
>Os0751#SINE#SINE-12_OS|SINE Os0751#SINE/unknown|SINE-12_OS ID=Os0751#SINE/unknown|SINE-12_OS;gene=SINE-12_OS;clade=SINE;evalue=4.9e-56;coverage=97.4;probability=0.89
AGGGGAAGCACAAGTGGTGTGGTGATAGAGTCGTGGGTGCATGACTCTACCCATAGGGTT
CAAATCCTGATGCCCACAAATATTACGCATATGCAGGTGTACTTTCAACAGGACTTTAGT
GAGATCAGGGATGTGTCGCTGGTTTCCGTCTCTTAGAGCATGTGTTAGGGGACGCATTCG
TGGGGGTGTGAGTGTGGTGTTGCGTGTGTAGTGGTGTGTGTGCGTGTGCGTCTGCCGTGT
AATCTCAAAAAAAAAA
>Os0751#SINE#SINE2-12_SBi|SINE Os0751#SINE/unknown|SINE2-12_SBi ID=Os0751#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=2e-09;coverage=82.2;probability=0.46
TAGAGTCGTGGGTGCATGACTCTACCCATAGGGTTCAAATCCTGATGCCCACAAATATTA
CGCATATGCAGGTGTACTTTCAACAGGACTTTAGTGAGATCAGGGATGTGTCGCTGGTTT
CCGTCTCTTAGAGCATGTGTTAGGGGACGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGT
GTGTAGTGGTGTGTGTGCGTGTGCGTCTGCCGTGTAATCTCAAAAAAAAAA
>Os0751#SINE#F524|SINE Os0751#SINE/unknown|F524 ID=Os0751#SINE/unknown|F524;gene=F524;clade=SINE;evalue=1.4e-07;coverage=27.4;probability=0.49
ACCCATAGGGTTCAAATCCTGATGCCCACAAATATTACGCATATGCAGGTGTACTTTCAA
CAGGACTTTAGTGAGATCAGGGATGTGTCGCTGGTTTCCGTCTCTTAGAGCATGTGTTAG
GGGACGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGTGTGTAGTGGTGTGTGTGCGTGTG
CGTCTGCCGTGTAATCTCAAAAAAAAAA
>Os0751#SINE#SINE9_OS|SINE Os0751#SINE/unknown|SINE9_OS ID=Os0751#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=4.4e-07;coverage=26.8;probability=0.56
ATAGGGTTCAAATCCTGATGCCCACAAATATTACGCATATGCAGGTGTACTTTCAACAGG
ACTTTAGTGAGATCAGGGATGTGTCGCTGGTTTCCGTCTCTTAGAGCATGTGTTAGGGGA
CGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGTGTGTAGTGGTGTGTGTGCGTGTGCGTC
TGCCGTGTAATCTCAAAAAAAAAA
>Os0751#SINE#SINE2-2_OS|SINE Os0751#SINE/unknown|SINE2-2_OS ID=Os0751#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=1.3e-14;coverage=43.2;probability=0.7
AATATTACGCATATGCAGGTGTACTTTCAACAGGACTTTAGTGAGATCAGGGATGTGTCG
CTGGTTTCCGTCTCTTAGAGCATGTGTTAGGGGACGCATTCGTGGGGGTGTGAGTGTGGT
GTTGCGTGTGTAGTGGTGTGTGTGCGTGTGCGTCTGCCGTGTAATCTCAAAAAAAAA
>Os0751#SINE#SINE2-1_OS|SINE Os0751#SINE/unknown|SINE2-1_OS ID=Os0751#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=1.4e-06;coverage=30.3;probability=0.71
CGCATATGCAGGTGTACTTTCAACAGGACTTTAGTGAGATCAGGGATGTGTCGCTGGTTT
CCGTCTCTTAGAGCATGTGTTAGGGGACGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGT
GTGTAGTGGTGTGTGTGCGTGTGCGTCTGCCGTGTAATCTCAAAAAAAAAA
>Os0751#SINE#SINE2-1_BDi|SINE Os0751#SINE/unknown|SINE2-1_BDi ID=Os0751#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=2.3e-09;coverage=35.0;probability=0.6
GCAGGTGTACTTTCAACAGGACTTTAGTGAGATCAGGGATGTGTCGCTGGTTTCCGTCTC
TTAGAGCATGTGTTAGGGGACGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGTGTGTAGT
GGTGTGTGTGCGTGTGCGTCTGCCGTGTAATCTCAAAAAAAAAA
>Os0751#SINE#SINE2-11_SBi|SINE Os0751#SINE/unknown|SINE2-11_SBi ID=Os0751#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=1e-06;coverage=30.3;probability=0.59
AGGTGTACTTTCAACAGGACTTTAGTGAGATCAGGGATGTGTCGCTGGTTTCCGTCTCTT
AGAGCATGTGTTAGGGGACGCATTCGTGGGGGTGTGAGTGTGGTGTTGCGTGTGTAGTGG
TGTGTGTGCGTGTGCGTCTGCCGTGTAATCTCAAAAAAAAAA
>Os0843#SINE#SHANSINE_MT|SINE Os0843#DNAnona/hAT|SHANSINE_MT ID=Os0843#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=4.4e-05;coverage=59.5;probability=0.61
CAGGGGCGAAGCTAGCATCAAAACAAGGGGGGTGCACTACCATTGAGAATCTAGAAAATT
TCAGTACAACACTGTACATTCTAGTGTTTTTAAGTGA
>Os0843#SINE#SINE1_SO|SINE Os0843#DNAnona/hAT|SINE1_SO ID=Os0843#DNAnona/hAT|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=6.8e-05;coverage=37.0;probability=0.54
GAAGCTAGCATCAAAACAAGGGGGGTGCACTACCATTGAGAATCTAGAAAATTTCAGTAC
AACACTGTACATTCTAGTGTTTTTAAGTGAGAAATTAGGAATTTAGGGGGGTTCATGTGC
ACCCCCCAAACACAATATAGCTTCGCCACTG
>Os0902#SINE#SHANSINE_MT|SINE Os0902#DNAnona/hAT|SHANSINE_MT ID=Os0902#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=3.7e-06;coverage=59.5;probability=0.65
CAGGGGCGGATCCAACTTGGGACATGGGGGTTCAGTTGAACCCCCAAACTTTTGGGTGAA
CAAACAAACTGTTATTACTTGAATTATTTATTTAAGAGAG
>Os0909#SINE#SINE2-3_OS|SINE Os0909#MITE/Stow|SINE2-3_OS ID=Os0909#MITE/Stow|SINE2-3_OS;gene=SINE2-3_OS;clade=SINE;evalue=3.4e-05;coverage=25.1;probability=0.63
AATTTACCACAATAACCCTATTTAATAACTACACTGCATACGCATATTCCATATGTATAC
TTGATTAAAAGAAAGGTTGAGGCACACATTCCA
>Os0986#SINE#SINE2-1_SBi|SINE Os0986#DNAnona/MULE|SINE2-1_SBi ID=Os0986#DNAnona/MULE|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.4e-05;coverage=22.0;probability=0.91
TTGCTCGATCAGTTGGTCAGGGCCGCTGGACAAGCCACCGGAGATCCTAGGTTCGATTCT
TTGCAGTACAATTTTATTTTCGTCAACCAAAATA
>Os0988_INT#SINE#SINE1R5_OS|SINE Os0988_INT#LTR/Copia|SINE1R5_OS ID=Os0988_INT#LTR/Copia|SINE1R5_OS;gene=SINE1R5_OS;clade=SINE;evalue=1.1e-06;coverage=70.0;probability=0.72
CCCACTTGCCTGCCGGCCTAGTGCCACACGGTGGTGGGCCGGATCCTTCGGATTGCGGCC
CACCACCCAATTTATTGTTTAAATTTAGTTTTTATTTTTATAACCCC
>Os0988_INT#SINE#SINE6_OS|SINE Os0988_INT#LTR/Copia|SINE6_OS ID=Os0988_INT#LTR/Copia|SINE6_OS;gene=SINE6_OS;clade=SINE;evalue=2.6e-07;coverage=71.8;probability=0.79
CTTGCCTGCCGGCCTAGTGCCACACGGTGGTGGGCCGGATCCTTCGGATTGCGGCCCACC
ACCCAATTTATTGTTTAAATTTAGTTTTTATTTTTATAAC
>Os1022#SINE#SINE2-1a_SBi|SINE Os1022#SINE/unknown|SINE2-1a_SBi ID=Os1022#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=4.8e-06;coverage=24.0;probability=0.74
AACAGCACCTAGCTCAGCTGGCAGGGAGCTGCCAGGAGCAGCGTGCTGGCCTGAGTTCGA
ATCCCTTTGAACGCAGGTTTT
>Os1022#SINE#SINE2-2_OS|SINE Os1022#SINE/unknown|SINE2-2_OS ID=Os1022#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=7.1e-06;coverage=32.7;probability=0.73
AACAGCACCTAGCTCAGCTGGCAGGGAGCTGCCAGGAGCAGCGTGCTGGCCTGAGTTCGA
ATCCCTTTGAACGCAGGTTTTCTCACCATTTTCTTCTCTATC
>Os1022#SINE#SINE2-1_SBi|SINE Os1022#SINE/unknown|SINE2-1_SBi ID=Os1022#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=0.00046;coverage=21.7;probability=0.63
ACCTAGCTCAGCTGGCAGGGAGCTGCCAGGAGCAGCGTGCTGGCCTGAGTTCGAATCCCT
TTGAACGCA
>Os1022#SINE#SINE1_MT|SINE Os1022#SINE/unknown|SINE1_MT ID=Os1022#SINE/unknown|SINE1_MT;gene=SINE1_MT;clade=SINE;evalue=5.2e-05;coverage=43.6;probability=0.63
GGAGCAGCGTGCTGGCCTGAGTTCGAATCCCTTTGAACGCAGGTTTTCTCACCATTTTCT
TCTCTATCAATACTGAATGCTAAGTTCCTCCTTAGTATTTCAAATTTTTTCCTTCAAAAA
AAAAAA
>Os1103#SINE#SHANSINE_MT|SINE Os1103#DNAnona/hAT|SHANSINE_MT ID=Os1103#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=1.3e-05;coverage=70.2;probability=0.63
CAGTGGCGGATCTAACATGGGACATGGGGGGGTTCAGTTGAACCCAACCCCCAAACTTTT
TGGGAACCATCAAACTGTTATTAGTATTATTTTAGGTTAA
>Os1181#SINE#SHANSINE_MT|SINE Os1181#DNAnona/hAT|SHANSINE_MT ID=Os1181#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=0.00022;coverage=71.1;probability=0.77
ACGGGCCCACAATGATTCATGGGTATTCAAATGAATACCCAAGATTTTTGAACAAAAAAT
ATATATATATGAAGTATATATTCCATATGTATATATGAA
>Os1262#SINE#SHANSINE_MT|SINE Os1262#DNAnona/hAT|SHANSINE_MT ID=Os1262#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=0.00026;coverage=76.9;probability=0.69
AGTGGGCGGAGCTACCATGATTCCCGGGTATTCCCGGGAATACCCAACTTTTTTATCGAA
AAACAAGTATATTTCTAATATATACATATGTACACATATTAGTGCACCTAAATCCTCAAT
TATTCGAT
>Os1296#SINE#SHANSINE_MT|SINE Os1296#DNAnona/hAT|SHANSINE_MT ID=Os1296#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=4.4e-05;coverage=76.9;probability=0.63
TGGGGCGGAGCCACCATGATTCCTGGGTATTCCCGGGAATACCCAACTTTTTTTATCAAA
AAATAAGTATACTTCTAGTATATACACATGTACACATATTAGTGCACCT
>Os1374#SINE#CASINE|SINE Os1374#SINE/unknown|CASINE ID=Os1374#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.6e-09;coverage=76.0;probability=0.7
GGAAGCAGGGATGTGCCGAGGTAGTAGGTTTTTTTTTTTTTTTGTTATGTGTTCTCCTCT
TTGTTGAGGTGTGAGTCTAAGTGCTCTTGTATCTTTTTGGCTGTGTATATCCTTCGTGGA
TATAGAGACTGGATTAATGAAAATCCATTATCTAAAAAA
>Os1374#SINE#OsSN3|SINE Os1374#SINE/unknown|OsSN3 ID=Os1374#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=0.00025;coverage=35.2;probability=0.49
AGTAGGTTTTTTTTTTTTTTTGTTATGTGTTCTCCTCTTTGTTGAGGTGTGAGTCTAAGT
GCTCTTGTATCTTTTTGGCTGTGTATATCCTTCGTGGATATAGAGACTGGATTAATGAAA
ATCCATTATCTAAAAAA
>Os1418#SINE#SHANSINE_MT|SINE Os1418#DNAnona/hAT|SHANSINE_MT ID=Os1418#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=0.00014;coverage=58.7;probability=0.64
CAGGGGCGGATCCAACTTGGGACATGGGGCAGTTGAACCCCCAAACTTTTGGGGGAACAA
ACAAACTGTTACTTGTATTAAGGTTAAGGCTCTGAAATTAAGA
>Os1424#SINE#CASINE|SINE Os1424#SINE/unknown|CASINE ID=Os1424#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=2.3e-05;coverage=22.9;probability=0.85
CTTTTGTTGTTCTTAAAACCTTTGTGCTGTCATCTCTTATGTAATGGGAGAGGTTAGTTG
ATGCATTTTGTACCCTTTTATTAGGGAGAGTCTTATGTACTCGTGTTCGGATTTTTGGCT
GTGTACACCCCACAAAGGTGTAGAGGCCGGGTTTGATAATCCTTTATCTAAAAAA
>Os1525_INT#SINE#SINE2-1_TAe|SINE Os1525_INT#LTR/Gypsy|SINE2-1_TAe ID=Os1525_INT#LTR/Gypsy|SINE2-1_TAe;gene=SINE2-1_TAe;clade=SINE;evalue=0.00036;coverage=33.1;probability=0.76
GATGAATCAGCTGTTGGCTTATGATCCTGAGGTTAATATGCGATACTTGATTCATCGTTT
TACTGAGGGATTACATAGAGAAATCAGAAATGCTGT
>Os1614#SINE#SINE9_OS|SINE Os1614#DNAnona/Helitron|SINE9_OS ID=Os1614#DNAnona/Helitron|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=4.6e-10;coverage=71.8;probability=0.63
ACAAATGTAAAGTGGGTATAGTTTAACTGGATAGGTTTCTTGTGGTGGAACTAGTCAACC
TGGATTTAAATATTTGATTTGACACGAGTGCTCGAGGCATTCGTCGTAACTTCGTCAATC
TCCATGCTCACGTCGTGAGCGCATTTTATACTATGTGTTTCTAAAAAAAATTATATTCTC
GCAATTCAAAATACATTGAGTACAAATATTCCACTCGTATTTTATTATACTTACCTACAT
AAAAAATAAATATTTTTCGTTCATGATACAAATTTCTATCCGTCGTCTTTTGGGCAAAGA
CAA
>Os1614#SINE#SINE2-1_BDi|SINE Os1614#DNAnona/Helitron|SINE2-1_BDi ID=Os1614#DNAnona/Helitron|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=1.2e-07;coverage=24.6;probability=0.88
CAAATGTAAAGTGGGTATAGTTTAACTGGATAGGTTTCTTGTGGTGGAACTAGTCAACCT
GGATTTAAATATTTGATTTGACACGAGTGCTCGAGGCATT
>Os1615#SINE#SINE1_SO|SINE Os1615#DNAnona/hAT|SINE1_SO ID=Os1615#DNAnona/hAT|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=1.9e-07;coverage=53.6;probability=0.63
CAGTGGCGAACCCAGAACAAAAGTTACCGGGGGTCCAATACATACTAATTATCTAATTAT
TGACTAATATATTAATTAATATAGTGTAATTTATATAGGATTTGAATAATCTACCCGGTG
TCCTGTGACACCGGGTAGTATAACCTAGGCACGCCCCT
>Os1661#SINE#SINE2-1_OS|SINE Os1661#SINE/unknown|SINE2-1_OS ID=Os1661#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=1.2e-36;coverage=84.7;probability=0.54
GAGAACCGAGCGTTGCTCGGTTGGCTAGCGTCGCCAGGTGAGCGAGCAGCCCGCGCGGGT
TCGATCCCTGGGATCGCAACTCGCGTCTCACCAGGGGTTTTTCCCCGTTTCCCTGGGACC
AACTTCGGTTGGTCCCAGTTAGGTAATAGGGTACACACACGCGTGCGTGTTCAGTGGTAC
TGTACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCTTATTCCTAGCGTGTGTTAGG
GACGCGCACGCGTGTGTGCGCGTGTTGTGGTGTGAGTGTGGTGTGTGTTCTCGTGTGCGT
CCTGAGTTGTAC
>Os1661#SINE#SINE2-2_OS|SINE Os1661#SINE/unknown|SINE2-2_OS ID=Os1661#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=6e-93;coverage=98.8;probability=0.93
AACCGAGCGTTGCTCGGTTGGCTAGCGTCGCCAGGTGAGCGAGCAGCCCGCGCGGGTTCG
ATCCCTGGGATCGCAACTCGCGTCTCACCAGGGGTTTTTCCCCGTTTCCCTGGGACCAAC
TTCGGTTGGTCCCAGTTAGGTAATAGGGTACACACACGCGTGCGTGTTCAGTGGTACTGT
ACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCTTATTCCTAGCGTGTGTTAGGGAC
GCGCACGCGTGTGTGCGCGTGTTGTGGTGTGAGTGTGGTGTGTGTTCTCGTGTGCGTCCT
GAGTTGTACCCTCTTAAAA
>Os1661#SINE#SINE-12_OS|SINE Os1661#SINE/unknown|SINE-12_OS ID=Os1661#SINE/unknown|SINE-12_OS;gene=SINE-12_OS;clade=SINE;evalue=1.5e-05;coverage=32.2;probability=0.61
ATAGGGTACACACACGCGTGCGTGTTCAGTGGTACTGTACGTTTCCCGTGCACTGAGGCC
TAGTGCCTCCAATCTTATTCCTAGCGTGTGTTAGGGACGCGCACGCGTGTGTGCGCGTGT
TGTGGTGTGAGTGTGGTGTGTGTTCTCGTGTGCGTCCTGAGTTGTA
>Os1867#SINE#SINE2-1_OS|SINE Os1867#SINE/unknown|SINE2-1_OS ID=Os1867#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=9.2e-16;coverage=84.4;probability=0.57
GACCGAGCGCTTGCTCAGGTGGCAAGCGTCGCCGGTGGGCACGCTGCCCATGAGCATTCG
AACCCCAGGTTCGACGCTCGTGCTCGCCCGGGGGATTTTTCCCCTCTTTCCCCGGACTGA
CTTTGGTTGGTCCTGGCTAGGTAATAGGGTACACACACGCGTGCGCGTTCAGTGGGACTG
CACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCTCATTCCTAGCGTGTGTTAGGGA
CGCGCACGCGTGTGTGTGCGTGTGTTGTGGTGTGAGTGTGGTGTGTGTAAGTGTGCGTTC
TGAATTGTACCCTTCTAAAAAAA
>Os1867#SINE#SINE2-2_OS|SINE Os1867#SINE/unknown|SINE2-2_OS ID=Os1867#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=7.2e-100;coverage=99.7;probability=0.95
ACCGAGCGCTTGCTCAGGTGGCAAGCGTCGCCGGTGGGCACGCTGCCCATGAGCATTCGA
ACCCCAGGTTCGACGCTCGTGCTCGCCCGGGGGATTTTTCCCCTCTTTCCCCGGACTGAC
TTTGGTTGGTCCTGGCTAGGTAATAGGGTACACACACGCGTGCGCGTTCAGTGGGACTGC
ACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCTCATTCCTAGCGTGTGTTAGGGAC
GCGCACGCGTGTGTGTGCGTGTGTTGTGGTGTGAGTGTGGTGTGTGTAAGTGTGCGTTCT
GAATTGTACCCTTCTAAAAAAA
>Os1867#SINE#SINE2-11_SBi|SINE Os1867#SINE/unknown|SINE2-11_SBi ID=Os1867#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=0.00033;coverage=23.9;probability=0.55
TTTCCCCGGACTGACTTTGGTTGGTCCTGGCTAGGTAATAGGGTACACACACGCGTGCGC
GTTCAGTGGGACTGCACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCTCATTCCTA
GCGTGTGTTAGGGACGCGCACGCGTGTGTGTGCGTGTGTTGTGGTGTGAGTGTGGTGTGT
GTAAGTGTGCGTTCTGAATTGTACCCTTCTAAAAAAAA
>Os1867#SINE#SINE-12_OS|SINE Os1867#SINE/unknown|SINE-12_OS ID=Os1867#SINE/unknown|SINE-12_OS;gene=SINE-12_OS;clade=SINE;evalue=7.6e-08;coverage=40.3;probability=0.66
AATAGGGTACACACACGCGTGCGCGTTCAGTGGGACTGCACGTTTCCCGTGCACTGAGGC
CTAGTGCCTCCAATCTCATTCCTAGCGTGTGTTAGGGACGCGCACGCGTGTGTGTGCGTG
TGTTGTGGTGTGAGTGTGGTGTGTGTAAGTGTGCGTTCTGAATTGTACCCTTCTAAAAAA
AA
>Os1867#SINE#F524|SINE Os1867#SINE/unknown|F524 ID=Os1867#SINE/unknown|F524;gene=F524;clade=SINE;evalue=1.7e-06;coverage=25.2;probability=0.74
GCGTGCGCGTTCAGTGGGACTGCACGTTTCCCGTGCACTGAGGCCTAGTGCCTCCAATCT
CATTCCTAGCGTGTGTTAGGGACGCGCACGCGTGTGTGTGCGTGTGTTGTGGTGTGAGTG
TGGTGTGTGTAAGTGTGCGTTCTGAATTGTACCCTTCTAAAAAAAA
>Os1867#SINE#SINE2-1_BDi|SINE Os1867#SINE/unknown|SINE2-1_BDi ID=Os1867#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=0.00042;coverage=24.0;probability=0.52
CAATCTCATTCCTAGCGTGTGTTAGGGACGCGCACGCGTGTGTGTGCGTGTGTTGTGGTG
TGAGTGTGGTGTGTGTAAGTGTGCGTTCTGAATTGTACCCTTCTAAAAAAAA
>Os1867#SINE#SINE2-12_SBi|SINE Os1867#SINE/unknown|SINE2-12_SBi ID=Os1867#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=3.4e-07;coverage=26.8;probability=0.73
TGTGTTAGGGACGCGCACGCGTGTGTGTGCGTGTGTTGTGGTGTGAGTGTGGTGTGTGTA
AGTGTGCGTTCTGAATTGTACCCTTCTAAAAAAAA
>Os2008#SINE#SHANSINE_MT|SINE Os2008#DNAnona/hAT|SHANSINE_MT ID=Os2008#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=3.1e-05;coverage=58.7;probability=0.75
CAGGGGCGGAGCCCAATAGGCCAGGGGGGTGCCCAGGAACCCGGCCCAAAATTTGAAATA
GCTTGTTACCCCTATATCTCCACCACATG
>Os2057#SINE#BoSB13|SINE Os2057#DNAnona/hAT|BoSB13 ID=Os2057#DNAnona/hAT|BoSB13;gene=BoSB13;clade=SINE;evalue=0.00023;coverage=25.9;probability=0.84
CCAAGTAGCCTGGTGGTTGGGGAGTTTACTAACTCCCATGTGGTCCTGGGTTCGAATCCC
ACCCATGCACATTTTCGCTCATTTTCCCCCACCAGCACCCTGCCGCGCGTACAACAGCGC
CAAGCCCGGTTCAAAGCGGTTTTATTCCCCGGTTTAATGGC
>Os2057#SINE#SINE2-1a_SBi|SINE Os2057#DNAnona/hAT|SINE2-1a_SBi ID=Os2057#DNAnona/hAT|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=2.5e-05;coverage=20.0;probability=0.82
AGTAGCCTGGTGGTTGGGGAGTTTACTAACTCCCATGTGGTCCTGGGTTCGAATCCCACC
CATGCACATTTTCGCTCATTTTCCCCCAC
>Os2393#SINE#CASINE|SINE Os2393#SINE/unknown|CASINE ID=Os2393#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=3.7e-06;coverage=23.4;probability=0.9
GTTTGTGACTTTTAGGCTGTGTACACCCTCACAAGGTGTAGAGGCCGGGTTTTTTATAAT
CCATTATCTAAAAAAAAA
>Os2523#SINE#SINE1_SO|SINE Os2523#DNAnona/hAT|SINE1_SO ID=Os2523#DNAnona/hAT|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=2.1e-05;coverage=67.3;probability=0.56
CAGTGACGGATCTAGAAATTTTTCTTAGCCTGAGAAAATCTAGCGATAAAAAACAAATTA
ACAAGTAAACACAAATACATATAGCATTTTATCATGGATAGAAGTAGAATTG
>Os2758#SINE#SINE9_OS|SINE Os2758#DNAnona/Helitron|SINE9_OS ID=Os2758#DNAnona/Helitron|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=2.9e-11;coverage=63.9;probability=0.59
AATTGCTAAGTGGGTATAGTTTACCTGGATAGGTTTCTTGTGGTGAAACCAGTCAATCTA
GATTCAAATCTTTGATTTGACACGGGTGCTCGAGGCGTTCGTGGTTACTTCGTCAATCTC
AATGCTCGTGTTGTGAGCGCGTTTGCACTATGTGTTTCTAAAAATATATATATTCTCGCA
ATTCAAAGTACATTGAGTACAAAAATTCCACTCGTGTTCTACATAAAAAATAAATATTTT
CGTTCATGATACCAATTTTCATCCGTCGCCTTTTGGGCAAAGACAATCGTATTATTCGTC
CATCCATTTTCTCCCGTGCTACAAATCATCCAAACTAAAGATCATTTCTACAAATAAAGA
GCAGATTATTTATCTAAAAGCAAACAATTTTTTTAGTAGATTAGTTGTCTAAACCAAACA
ACACTTTTTTCA
>Os2758#SINE#SINE2-1_BDi|SINE Os2758#DNAnona/Helitron|SINE2-1_BDi ID=Os2758#DNAnona/Helitron|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=7.5e-11;coverage=23.4;probability=0.86
AATTGCTAAGTGGGTATAGTTTACCTGGATAGGTTTCTTGTGGTGAAACCAGTCAATCTA
GATTCAAATCTTTGATTTGACACGGGTGCTCGAG
>Os2861#SINE#SINE_SO|SINE Os2861#DNAnona/CACTG|SINE_SO ID=Os2861#DNAnona/CACTG|SINE_SO;gene=SINE_SO;clade=SINE;evalue=1.8e-06;coverage=97.4;probability=0.26
TAGTGGCCTGGCCCCCTCCAACAATTATTTTCACACATAATCATCTAACTAATTAGGTAA
TTAACCTAAGTAAAAGTATATTTTGCCCCCTCCAAGATTCTTAGGCCCCTCCCATGTCTA
AATCCTGGCTCCGCCACTGG
>Os2861#SINE#SINE1_SO|SINE Os2861#DNAnona/CACTG|SINE1_SO ID=Os2861#DNAnona/CACTG|SINE1_SO;gene=SINE1_SO;clade=SINE;evalue=3.6e-05;coverage=58.3;probability=0.51
CTCCAACAATTATTTTCACACATAATCATCTAACTAATTAGGTAATTAACCTAAGTAAAA
GTATATTTTGCCCCCTCCAAGATTCTTAGGCCCCTCCCATGTCTAAATCCTGGCTCCGCC
ACTGG
>Os3264#SINE#BoSB14A|SINE Os3264#DNAauto/MLE|BoSB14A ID=Os3264#DNAauto/MLE|BoSB14A;gene=BoSB14A;clade=SINE;evalue=0.00018;coverage=26.3;probability=0.74
TGTTGCGAGTACCTGGGTTCGATTCCCGGTGGCCACTTTTATTTTGCTGGTTGCTTCATT
TTACATGGGAATGTTTGGGCCCT
>Os3527_ICR#SINE#SHANSINE_MT|SINE Os3527_ICR#DNAnona/hAT|SHANSINE_MT ID=Os3527_ICR#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=3.5e-06;coverage=70.2;probability=0.72
CAGGGGCGGGCCCACAGTTATTCATGGGTATTCAAATGAATACCCAAGATTTTTGCAGAA
AAAATACATATATGAAGTATATATTTCATATTTGTGTGTG
>Os3538_LTR#SINE#SINE2-1_SBi|SINE Os3538_LTR#LTR/unknown|SINE2-1_SBi ID=Os3538_LTR#LTR/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=9.7e-05;coverage=30.1;probability=0.68
GTATCAAAGCCAGAGGTCTCGAGTTCGAATCCTGGCTGGCGCGCAATTAAATAAAATAAT
TGCAGCCCACTCCAATATTCCACGCTTGAGACTTGAGGGGGTCTCGCGTGAGGGGGAGTG
TTGGAGTGTATAAAGTGAATTGCCCATCTTTCCCT
>Os3594#SINE#SHANSINE_MT|SINE Os3594#DNAnona/hAT|SHANSINE_MT ID=Os3594#DNAnona/hAT|SHANSINE_MT;gene=SHANSINE_MT;clade=SINE;evalue=0.00015;coverage=29.8;probability=0.82
CAGTGGCGAAGCTAGAACAAATTAGAGGGGGTGCACCACCTCAACCGTATATGTAGTAGC
ACATGAAATTTTGAAG
>RST-Osativa-Cluster_0#SINE#F524|SINE RST-Osativa-Cluster_0#SINE/unknown|F524 ID=RST-Osativa-Cluster_0#SINE/unknown|F524;gene=F524;clade=SINE;evalue=5.8e-122;coverage=81.0;probability=0.93
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCCAGGATTTGCC
GGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGGTTCATAGGGGTGA
GGCGCTGTGGTGACTTCGT
>RST-Osativa-Cluster_0#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=5e-21;coverage=30.7;probability=0.87
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
>RST-Osativa-Cluster_0#SINE#OsSN3|SINE RST-Osativa-Cluster_0#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_0#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=1.6e-17;coverage=38.2;probability=0.95
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTG
>RST-Osativa-Cluster_0#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=3.8e-09;coverage=26.8;probability=0.83
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACG
>RST-Osativa-Cluster_0#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=4e-11;coverage=24.1;probability=0.85
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GTACCCGTCGA
>RST-Osativa-Cluster_0#SINE#AtSB4|SINE RST-Osativa-Cluster_0#SINE/unknown|AtSB4 ID=RST-Osativa-Cluster_0#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=3.5e-05;coverage=52.8;probability=0.72
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GT
>RST-Osativa-Cluster_0#SINE#BoSB10A|SINE RST-Osativa-Cluster_0#SINE/unknown|BoSB10A ID=RST-Osativa-Cluster_0#SINE/unknown|BoSB10A;gene=BoSB10A;clade=SINE;evalue=9.6e-05;coverage=36.0;probability=0.89
AAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGAC
TCCCCATGGGA
>RST-Osativa-Cluster_0#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=1.4e-16;coverage=24.2;probability=0.87
GGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTC
CCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTA
CCCGT
>RST-Osativa-Cluster_0#SINE#CASINE|SINE RST-Osativa-Cluster_0#SINE/unknown|CASINE ID=RST-Osativa-Cluster_0#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=3.1e-05;coverage=28.6;probability=0.79
TTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTT
CCAGGATTTAACGGCGTTGTGCTTTCAGT
>RST-Osativa-Cluster_0#SINE#SINE2-11_SBi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-11_SBi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=3.3e-22;coverage=56.0;probability=0.64
AGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACG
GCGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTT
CGTCAATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTT
GCGTGCGTGGTTCATAGGGGTGAGG
>RST-Osativa-Cluster_0#SINE#SINE2-1_BDi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-1_BDi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=2.2e-63;coverage=51.1;probability=0.85
CACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTT
GTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCA
ATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTG
CGTGGTTCATAGGGGTGAGGCGC
>RST-Osativa-Cluster_0#SINE#SINE2-12_SBi|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE2-12_SBi ID=RST-Osativa-Cluster_0#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=1.7e-68;coverage=65.1;probability=0.78
CTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTG
CTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATC
TCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGT
GGTTCATAGGGGTGAGGCG
>RST-Osativa-Cluster_0#SINE#SINE9_OS|SINE RST-Osativa-Cluster_0#SINE/unknown|SINE9_OS ID=RST-Osativa-Cluster_0#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=2.4e-30;coverage=22.6;probability=0.77
AATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGC
GAGGCGCCTGTGGTGACTTCGTCAATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGAT
GCTCATAGGGGTAGGGTTTGCGTGCGTGGTTCATAGGGGTGAGGCGC
>RST-Osativa-Cluster_1#SINE#F524|SINE RST-Osativa-Cluster_1#SINE/unknown|F524 ID=RST-Osativa-Cluster_1#SINE/unknown|F524;gene=F524;clade=SINE;evalue=1.2e-101;coverage=89.7;probability=0.97
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCCAGGATTTGCC
GGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTG
AGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAA
>RST-Osativa-Cluster_1#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=2.9e-21;coverage=30.7;probability=0.87
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
>RST-Osativa-Cluster_1#SINE#OsSN3|SINE RST-Osativa-Cluster_1#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_1#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=9.4e-18;coverage=38.2;probability=0.95
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTG
>RST-Osativa-Cluster_1#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=2.8e-09;coverage=26.8;probability=0.83
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACG
>RST-Osativa-Cluster_1#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.6e-11;coverage=24.1;probability=0.88
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCCAGGATTTGCCGGC
CCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTGAGT
G
>RST-Osativa-Cluster_1#SINE#AtSB4|SINE RST-Osativa-Cluster_1#SINE/unknown|AtSB4 ID=RST-Osativa-Cluster_1#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=2.5e-05;coverage=52.8;probability=0.72
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GT
>RST-Osativa-Cluster_1#SINE#BoSB10A|SINE RST-Osativa-Cluster_1#SINE/unknown|BoSB10A ID=RST-Osativa-Cluster_1#SINE/unknown|BoSB10A;gene=BoSB10A;clade=SINE;evalue=6.3e-05;coverage=36.0;probability=0.9
AAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGAC
TCCCCATGGGAGCGAATTTTCCAG
>RST-Osativa-Cluster_1#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=9.4e-17;coverage=24.2;probability=0.86
GGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTC
CCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTA
CCCGTCGA
>RST-Osativa-Cluster_1#SINE#CASINE|SINE RST-Osativa-Cluster_1#SINE/unknown|CASINE ID=RST-Osativa-Cluster_1#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.8e-05;coverage=29.1;probability=0.78
GTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTT
TCCAGGATTTAACGGCGTTGTGCTTTCAGT
>RST-Osativa-Cluster_1#SINE#SINE2-11_SBi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-11_SBi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=8.3e-18;coverage=72.2;probability=0.67
CAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAAC
GGCGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACT
TCGTCAATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTT
TGCGTGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGT
GTAATTCTCAAA
>RST-Osativa-Cluster_1#SINE#SINE2-12_SBi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-12_SBi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=4.5e-52;coverage=80.1;probability=0.82
TAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGC
GTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCG
TCAATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGC
GTGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTA
ATTCTCAAA
>RST-Osativa-Cluster_1#SINE#SINE2-1_BDi|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_BDi ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=4.8e-47;coverage=65.3;probability=0.86
CACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTT
GTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCA
ATCTCTCCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTG
CGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATT
CTCAAA
>RST-Osativa-Cluster_1#SINE#SINE2-1_OS|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_OS ID=RST-Osativa-Cluster_1#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=1.7e-08;coverage=43.2;probability=0.75
GTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTC
AGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCC
AGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGTGTT
CATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAAT
>RST-Osativa-Cluster_1#SINE#SINE9_OS|SINE RST-Osativa-Cluster_1#SINE/unknown|SINE9_OS ID=RST-Osativa-Cluster_1#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=6.9e-23;coverage=29.6;probability=0.74
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCCAGGATTTGCCGGC
CCAGTCTTCGAAGATGCTCATAGGGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTGAGT
GCGCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTCAAA
>RST-Osativa-Cluster_10#SINE#SINE2-11_OS|SINE RST-Osativa-Cluster_10#SINE/unknown|SINE2-11_OS ID=RST-Osativa-Cluster_10#SINE/unknown|SINE2-11_OS;gene=SINE2-11_OS;clade=SINE;evalue=1.3e-39;coverage=85.8;probability=0.93
AGAGATGCACTTGATAGTGCAGTGGCAAGGGGTGTGTGGTTTCAACCCCGAGGTCCCGTG
TTCAATCCCCAACACGCTCACAATTTCTTCTTAAAAAATGTTTGGAGGGACATCTCTCCC
TCCAAATCTCTC
>RST-Osativa-Cluster_10#SINE#SINE2-3_OS|SINE RST-Osativa-Cluster_10#SINE/unknown|SINE2-3_OS ID=RST-Osativa-Cluster_10#SINE/unknown|SINE2-3_OS;gene=SINE2-3_OS;clade=SINE;evalue=2.4e-06;coverage=48.0;probability=0.76
CTTGATAGTGCAGTGGCAAGGGGTGTGTGGTTTCAACCCCGAGGTCCCGTGTTCAATCCC
CAACACGCTCACAATTTCTTCTTAAAAAATGTTTGGAGGGACATCTCTCCCTCCA
>RST-Osativa-Cluster_11#SINE#SINE2-11_OS|SINE RST-Osativa-Cluster_11#SINE/unknown|SINE2-11_OS ID=RST-Osativa-Cluster_11#SINE/unknown|SINE2-11_OS;gene=SINE2-11_OS;clade=SINE;evalue=5.4e-25;coverage=85.2;probability=0.8
GAGATGCACTTGATAGTGCAGTGGAAGGTGTGTGGTTTAACCGATCTGTTAATCCAACAC
GCTCACAATTTCTTCTTAAAAATTTTGGAGGGAGTCTCTCCCTCCAAATCTC
>RST-Osativa-Cluster_12#SINE#SINE1R5_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|SINE1R5_OS ID=RST-Osativa-Cluster_12#SINE/unknown|SINE1R5_OS;gene=SINE1R5_OS;clade=SINE;evalue=4.9e-30;coverage=90.0;probability=0.91
GAGAAAGCCAGGGGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCA
AGCCTCACCCCTCTAATTATTTGATATTAGGTCTTCCCTATAATATTCCG
>RST-Osativa-Cluster_12#SINE#SINE1_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|SINE1_OS ID=RST-Osativa-Cluster_12#SINE/unknown|SINE1_OS;gene=SINE1_OS;clade=SINE;evalue=4.1e-26;coverage=88.5;probability=0.89
GAGAAAGCCAGGGGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCA
AGCCTCACCCCTCTAATTATTTGATATTAGGTCTTCCCTATAATATTCCG
>RST-Osativa-Cluster_12#SINE#p-SINE1_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|p-SINE1_OS ID=RST-Osativa-Cluster_12#SINE/unknown|p-SINE1_OS;gene=p-SINE1_OS;clade=SINE;evalue=3.6e-25;coverage=66.9;probability=0.82
GAGAAAGCCAGGGGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCA
AGCCTCACCCCTCTAATTATTTGATATTAGGTCTTCCCTATAATATTCC
>RST-Osativa-Cluster_12#SINE#SINE6_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|SINE6_OS ID=RST-Osativa-Cluster_12#SINE/unknown|SINE6_OS;gene=SINE6_OS;clade=SINE;evalue=8.5e-26;coverage=88.9;probability=0.84
AGAAAGCCAGGGGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCAA
GCCTCACCCCTCTAATTATTTGATATTAGGTCTTCCCTATAATATTCC
>RST-Osativa-Cluster_12#SINE#SINE8_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|SINE8_OS ID=RST-Osativa-Cluster_12#SINE/unknown|SINE8_OS;gene=SINE8_OS;clade=SINE;evalue=1.6e-23;coverage=84.2;probability=0.84
AGAAAGCCAGGGGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCAA
GCCTCACCCCTCTAATTATTTGATATTAGGTCTTCCCTATAATATTCCG
>RST-Osativa-Cluster_12#SINE#SINE16_OS|SINE RST-Osativa-Cluster_12#SINE/unknown|SINE16_OS ID=RST-Osativa-Cluster_12#SINE/unknown|SINE16_OS;gene=SINE16_OS;clade=SINE;evalue=8.9e-13;coverage=73.3;probability=0.8
GGTCTTCGGCTAGCTCCACAAGGTGGTGGGCTAGACGACCTGGGTTCAAGCCTCACCCCT
CTAATTATTTGATATTAGGTCTTCCCTATAATATTC
>RST-Osativa-Cluster_2#SINE#SINE2-1_BDi|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE2-1_BDi ID=RST-Osativa-Cluster_2#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=8.8e-71;coverage=92.7;probability=0.87
GCGAAGTGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTT
CAAATCCTAGATTTGACACGGGTGCTCGCATTTACGGCTAATTATTCTTTCAGTGGTAGG
CGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCAAGATATGTCGG
CCCAGTCTTCCGGAGGTGCTCATAGGGGTAGGGTGTGCGTGTGTGCGTTCATAGGGGTGA
GTGTGCGCACGTTGTGAGCGCCTGCGTTTGTACTGTGTTTCTCAAAA
>RST-Osativa-Cluster_2#SINE#SINE9_OS|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE9_OS ID=RST-Osativa-Cluster_2#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=1.8e-63;coverage=52.7;probability=0.86
GCGAAGTGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTT
CAAATCCTAGATTTGACACGGGTGCTCGCATTTACGGCTAATTATTCTTTCAGTGGTAGG
CGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCAAGATATGTCGG
CCCAGTCTTCCGGAGGTGCTCATAGGGGTAGGGTGTGCGTGTGTGCGTTCATAGGGGTGA
GTGTGCGCACGTTGTGAGCGCCTGCGTTTGTACTGTGTTTCTCAAAA
>RST-Osativa-Cluster_2#SINE#SINE2-11_SBi|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE2-11_SBi ID=RST-Osativa-Cluster_2#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=2.1e-35;coverage=94.2;probability=0.79
GCGAAGTGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTT
CAAATCCTAGATTTGACACGGGTGCTCGCATTTACGGCTAATTATTCTTTCAGTGGTAGG
CGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCAAGATATGTCGG
CCCAGTCTTCCGGAGGTGCTCATAGGGGTAGGGTGTGCGTGTGTGCGTTCATAGGGGTGA
GTGTGCGCACGTTGTGAGCGCCTGCGTTTGTACTGTGTTTCTCAAAA
>RST-Osativa-Cluster_2#SINE#SINE2-1_OS|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE2-1_OS ID=RST-Osativa-Cluster_2#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=8.1e-12;coverage=83.3;probability=0.69
GCGAAGTGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTT
CAAATCCTAGATTTGACACGGGTGCTCGCATTTACGGCTAATTATTCTTTCAGTGGTAGG
CGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCAAGATATGTCGG
CCCAGTCTTCCGGAGGTGCTCATAGGGGTAGGGTGTGCGTGTGTGCGTTCATAGGGGTGA
GTGTGCGCACGTTGTGAGCGCCTGCGTTTGTACTGTGTTTC
>RST-Osativa-Cluster_2#SINE#SINE2-12_SBi|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE2-12_SBi ID=RST-Osativa-Cluster_2#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=9.1e-54;coverage=94.4;probability=0.83
CGAAGTGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTTC
AAATCCTAGATTTGACACGGGTGCTCGCATTTACGGCTAATTATTCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCAAGATATGTCGGC
CCAGTCTTCCGGAGGTGCTCATAGGGGTAGGGTGTGCGTGTGTGCGTTCATAGGGGTGAG
TGTGCGCACGTTGTGAGCGCCTGCGTTTGTACTGTGTTTCTCAAAA
>RST-Osativa-Cluster_2#SINE#SINE2-2_OS|SINE RST-Osativa-Cluster_2#SINE/unknown|SINE2-2_OS ID=RST-Osativa-Cluster_2#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=6.3e-09;coverage=23.4;probability=0.91
TGAGCATAGCTCAACTGGTTAGGTTCCTTGTGGTGGAACCAGCCCACCCGGGTTCAAATC
CTAGATTTGACACGGGTGCTCGCATTTACGGC
>RST-Osativa-Cluster_2#SINE#F524|SINE RST-Osativa-Cluster_2#SINE/unknown|F524 ID=RST-Osativa-Cluster_2#SINE/unknown|F524;gene=F524;clade=SINE;evalue=1.9e-46;coverage=72.6;probability=0.88
CCTTGTGGTGGAACCAGCCCACCCGGGTTCAAATCCTAGATTTGACACGGGTGCTCGCAT
TTACGGCTAATTATTCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTG
GTGACTTCGTCAATCTCAAGATATGTCGGCCCAGTCTTCCGGAGGTGCTCATAGGGGTAG
GGTGTGCGTGTGTGCGTTCATAGGGGTGAGTGTGCGCACGTTGTGAGCGCCTGCGTTTGT
ACTGTGTTTCTCAAAA
>RST-Osativa-Cluster_3#SINE#F524|SINE RST-Osativa-Cluster_3#SINE/unknown|F524 ID=RST-Osativa-Cluster_3#SINE/unknown|F524;gene=F524;clade=SINE;evalue=3.4e-87;coverage=89.1;probability=0.96
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCAGGATTTGCCG
GCCCAGTCTTCGAAGATGCTCATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTG
TACTGTGTAATTCTAA
>RST-Osativa-Cluster_3#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=3.4e-21;coverage=30.7;probability=0.87
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
>RST-Osativa-Cluster_3#SINE#OsSN3|SINE RST-Osativa-Cluster_3#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_3#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=7.5e-18;coverage=38.2;probability=0.95
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGC
>RST-Osativa-Cluster_3#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=3e-09;coverage=26.8;probability=0.83
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACG
>RST-Osativa-Cluster_3#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=3.1e-11;coverage=24.5;probability=0.83
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTG
>RST-Osativa-Cluster_3#SINE#AtSB4|SINE RST-Osativa-Cluster_3#SINE/unknown|AtSB4 ID=RST-Osativa-Cluster_3#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=1.8e-05;coverage=52.8;probability=0.72
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GT
>RST-Osativa-Cluster_3#SINE#BoSB10A|SINE RST-Osativa-Cluster_3#SINE/unknown|BoSB10A ID=RST-Osativa-Cluster_3#SINE/unknown|BoSB10A;gene=BoSB10A;clade=SINE;evalue=5.5e-05;coverage=36.0;probability=0.91
AAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGAC
TCCCCATGGGAGCGAATTTTCCAGGATTTA
>RST-Osativa-Cluster_3#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=8.7e-17;coverage=24.2;probability=0.86
GGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTC
CCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTA
CCCGTCGAC
>RST-Osativa-Cluster_3#SINE#CASINE|SINE RST-Osativa-Cluster_3#SINE/unknown|CASINE ID=RST-Osativa-Cluster_3#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.7e-05;coverage=29.1;probability=0.78
GTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTT
TCCAGGATTTAACGGCGTTGTGCTTTCAGT
>RST-Osativa-Cluster_3#SINE#SINE2-11_SBi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-11_SBi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=1.7e-15;coverage=75.2;probability=0.67
TCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
CGGCGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGAC
TTCGTCAATCTCTCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTGAGTGC
GCGTGCGTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTAA
>RST-Osativa-Cluster_3#SINE#SINE2-1_BDi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-1_BDi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=1.9e-40;coverage=65.3;probability=0.86
GCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGT
TGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTC
AATCTCTCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTGAGTGCGCGTGC
GTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTAA
>RST-Osativa-Cluster_3#SINE#SINE2-12_SBi|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE2-12_SBi ID=RST-Osativa-Cluster_3#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=7.7e-39;coverage=79.4;probability=0.79
GCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGT
TGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTC
AATCTCTCAGGATTTGCCGGCCCAGTCTTCGAAGATGCTCATAGGGGTGAGTGCGCGTGC
GTTGTGAGTGTCTGCGTTGTACTGTGTAATTCTAA
>RST-Osativa-Cluster_3#SINE#SINE9_OS|SINE RST-Osativa-Cluster_3#SINE/unknown|SINE9_OS ID=RST-Osativa-Cluster_3#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=7.4e-19;coverage=29.1;probability=0.67
ACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGA
CGTACCCGTCGACAGCGAGGCGCCTGTGGTGACTTCGTCAATCTCTCAGGATTTGCCGGC
CCAGTCTTCGAAGATGCTCATAGGGGTGAGTGCGCGTGCGTTGTGAGTGTCTGCGTTGTA
CTGTGTAATTCTAA
>RST-Osativa-Cluster_4#SINE#F524|SINE RST-Osativa-Cluster_4#SINE/unknown|F524 ID=RST-Osativa-Cluster_4#SINE/unknown|F524;gene=F524;clade=SINE;evalue=6.8e-89;coverage=88.5;probability=0.98
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGC
GACGTACCCGTCGACAGCGCGGCCCAGTCTTCGAAGATGCTCATAGAGGTAGGGTTTGCG
TGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTAAGTGTCTGCGTTGTACTGTGTAA
TTCTCT
>RST-Osativa-Cluster_4#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=2.7e-21;coverage=30.7;probability=0.87
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
>RST-Osativa-Cluster_4#SINE#OsSN3|SINE RST-Osativa-Cluster_4#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_4#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=6.5e-18;coverage=38.2;probability=0.95
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCA
>RST-Osativa-Cluster_4#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=2.1e-09;coverage=26.8;probability=0.83
GCGAAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTT
CGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGG
>RST-Osativa-Cluster_4#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.3e-11;coverage=24.5;probability=0.87
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GTACCCGTCGACAGCGCGGCCCAGTCTTCGAAGATGCTCATAGAGGTAGGGTTTGCGTGC
GTGTGTTC
>RST-Osativa-Cluster_4#SINE#AtSB4|SINE RST-Osativa-Cluster_4#SINE/unknown|AtSB4 ID=RST-Osativa-Cluster_4#SINE/unknown|AtSB4;gene=AtSB4;clade=SINE;evalue=1.9e-05;coverage=52.8;probability=0.72
AAAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGA
CTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGAC
GT
>RST-Osativa-Cluster_4#SINE#BoSB10A|SINE RST-Osativa-Cluster_4#SINE/unknown|BoSB10A ID=RST-Osativa-Cluster_4#SINE/unknown|BoSB10A;gene=BoSB10A;clade=SINE;evalue=4.9e-05;coverage=36.0;probability=0.91
AAGGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGAC
TCCCCATGGGAGCGAATTTTCCAGGATTTAA
>RST-Osativa-Cluster_4#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=8.1e-17;coverage=24.2;probability=0.86
GGGCCTGTAGCCTAGTGGTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTC
CCCATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTA
>RST-Osativa-Cluster_4#SINE#CASINE|SINE RST-Osativa-Cluster_4#SINE/unknown|CASINE ID=RST-Osativa-Cluster_4#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.4e-05;coverage=29.1;probability=0.78
GTTACAAGAGCCTCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTT
TCCAGGATTTAACGGCGTTGTGCTTTCAGTG
>RST-Osativa-Cluster_4#SINE#SINE2-11_SBi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-11_SBi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-11_SBi;gene=SINE2-11_SBi;clade=SINE;evalue=2.7e-10;coverage=75.5;probability=0.58
TCAGTAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAA
CGGCGTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGCGGCCCAGTCTTCGAA
GATGCTCATAGAGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTG
TAAGTGTCTGCGTTGTACTGTGTAATTCTCT
>RST-Osativa-Cluster_4#SINE#SINE2-12_SBi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-12_SBi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-12_SBi;gene=SINE2-12_SBi;clade=SINE;evalue=2.8e-37;coverage=79.1;probability=0.79
TAGCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGC
GTTGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGCGGCCCAGTCTTCGAAGATG
CTCATAGAGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTAAG
TGTCTGCGTTGTACTGTGTAATTCTCT
>RST-Osativa-Cluster_4#SINE#SINE2-1_BDi|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE2-1_BDi ID=RST-Osativa-Cluster_4#SINE/unknown|SINE2-1_BDi;gene=SINE2-1_BDi;clade=SINE;evalue=3e-32;coverage=65.3;probability=0.85
GCACCTGAGGTCCTGGGTTCGACTCCCCATGGGAGCGAATTTTCCAGGATTTAACGGCGT
TGTGCTTTCAGTGGTAGGCGACGTACCCGTCGACAGCGCGGCCCAGTCTTCGAAGATGCT
CATAGAGGTAGGGTTTGCGTGCGTGTGTTCATAGGGGTGAGTGCGCGTGCGTTGTAAGTG
TCTGCGTTGTACTGTGTAATT
>RST-Osativa-Cluster_4#SINE#SINE9_OS|SINE RST-Osativa-Cluster_4#SINE/unknown|SINE9_OS ID=RST-Osativa-Cluster_4#SINE/unknown|SINE9_OS;gene=SINE9_OS;clade=SINE;evalue=6.1e-12;coverage=29.2;probability=0.69
ATGGGAGCGAATTTTCCAGGATTTAACGGCGTTGTGCTTTCAGTGGTAGGCGACGTACCC
GTCGACAGCGCGGCCCAGTCTTCGAAGATGCTCATAGAGGTAGGGTTTGCGTGCGTGTGT
TCATAGGGGTGAGTGCGCGTGCGTTGTAAGTGTCTGCGTTGTACTGTGTAATTCT
>RST-Osativa-Cluster_5#SINE#OsSN3|SINE RST-Osativa-Cluster_5#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_5#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=5.6e-64;coverage=78.1;probability=0.94
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTG
ATAGGCTAAGTTCCTAATTTAAAAAGGCTGCATATATCCGGTTGGATATAGAGGCCGGGT
AAAAAATACCCTTCTCTCT
>RST-Osativa-Cluster_5#SINE#F524|SINE RST-Osativa-Cluster_5#SINE/unknown|F524 ID=RST-Osativa-Cluster_5#SINE/unknown|F524;gene=F524;clade=SINE;evalue=5.5e-19;coverage=38.9;probability=0.8
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTG
ATAGGCTAAGTTCCTAATTTAAAAAGGCTGCATATATCCGGTTGGATATAGAGGCCGGGT
AA
>RST-Osativa-Cluster_5#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_5#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_5#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=8.1e-19;coverage=33.0;probability=0.87
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTG
ATAGGCTAAGTTCCTAATTTAAAAAGGCTGCATATATCCGGTTGGATATAGAGGCCGGGT
AAAAAATACCCTTCTCTCT
>RST-Osativa-Cluster_5#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_5#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_5#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=1.4e-08;coverage=30.5;probability=0.79
GAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTC
AAATCTCCATAGGAGCGAATTTCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTGAT
AGGCTAAGTTC
>RST-Osativa-Cluster_5#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_5#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_5#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=9e-19;coverage=27.6;probability=0.85
GGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAAT
CTCCATAGGAGCGAATTTCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTGATAGGC
TAAGTTCCTAATTTAAAAAGGCTGCATATATCCGGTTGGATATAGAGGCCGGGTAAAAAA
TACCCTTC
>RST-Osativa-Cluster_5#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_5#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_5#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=2.2e-15;coverage=24.1;probability=0.85
TAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAATCTCCATA
GGAGCGAATTTCAGATTGGGTTATTTGA
>RST-Osativa-Cluster_5#SINE#CASINE|SINE RST-Osativa-Cluster_5#SINE/unknown|CASINE ID=RST-Osativa-Cluster_5#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=2.5e-45;coverage=55.4;probability=0.95
GTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATT
TCAGATTGGGTTATTTGAGGGCTAAGTTCCCTATTTGATAGG
>RST-Osativa-Cluster_6#SINE#OsSN3|SINE RST-Osativa-Cluster_6#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_6#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=8.3e-60;coverage=82.0;probability=0.93
ACGAAAGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGT
TCAAATCTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTT
CAATGGCCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCTAAAA
AAAATAT
>RST-Osativa-Cluster_6#SINE#F524|SINE RST-Osativa-Cluster_6#SINE/unknown|F524 ID=RST-Osativa-Cluster_6#SINE/unknown|F524;gene=F524;clade=SINE;evalue=2.9e-17;coverage=35.2;probability=0.73
ACGAAAGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGT
TCAAATCTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTT
CAATGGCCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCTAAAA
AAAA
>RST-Osativa-Cluster_6#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_6#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_6#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=9.5e-18;coverage=33.3;probability=0.76
CGAAAGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTT
CAAATCTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTC
AATGGCCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAA
AAAT
>RST-Osativa-Cluster_6#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_6#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_6#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=3.7e-09;coverage=30.2;probability=0.83
CGAAAGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTT
CAAATCTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTC
AATGGCCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCTA
>RST-Osativa-Cluster_6#SINE#BoSB8A|SINE RST-Osativa-Cluster_6#SINE/unknown|BoSB8A ID=RST-Osativa-Cluster_6#SINE/unknown|BoSB8A;gene=BoSB8A;clade=SINE;evalue=0.00036;coverage=63.2;probability=0.76
AAAGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCA
AATCTCCTATGGAGCGAATTTCAGATT
>RST-Osativa-Cluster_6#SINE#BoSB6D|SINE RST-Osativa-Cluster_6#SINE/unknown|BoSB6D ID=RST-Osativa-Cluster_6#SINE/unknown|BoSB6D;gene=BoSB6D;clade=SINE;evalue=0.00025;coverage=34.4;probability=0.67
AGGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCAAA
TCTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTCAATG
GCCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAAAAAT
A
>RST-Osativa-Cluster_6#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_6#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_6#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=7.7e-18;coverage=27.0;probability=0.91
GGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCAAAT
CTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTCAATGG
C
>RST-Osativa-Cluster_6#SINE#SINEX-5_CR|SINE RST-Osativa-Cluster_6#SINE/unknown|SINEX-5_CR ID=RST-Osativa-Cluster_6#SINE/unknown|SINEX-5_CR;gene=SINEX-5_CR;clade=SINE;evalue=0.00038;coverage=35.7;probability=0.69
GGGCATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCAAAT
CTCCTATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTCAATGG
CCGTATATATCCGGTTGGATATAGAGGCCGGGTAAAAAATACCCTTCTCT
>RST-Osativa-Cluster_6#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_6#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_6#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=5.4e-12;coverage=26.2;probability=0.82
ATGTAGCCTAGTGGTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCAAATCTCC
TATGGAGCGAATTTCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTCAATGGCCGT
>RST-Osativa-Cluster_6#SINE#CASINE|SINE RST-Osativa-Cluster_6#SINE/unknown|CASINE ID=RST-Osativa-Cluster_6#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.6e-56;coverage=93.7;probability=0.96
GTTACAGTGACCTGAGTAGTACCCCAAGGTCCTGAGTTCAAATCTCCTATGGAGCGAATT
TCAGATTGGGTTGTTTGCGGGGCTAAGTTCCCTATTTCAATGGCCGTATATATCCGGTTG
GATATAGAGGCCGGGTAAAAAATACCCTTCTCTAAAAAAAATAT
>RST-Osativa-Cluster_7#SINE#OsSN3|SINE RST-Osativa-Cluster_7#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_7#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=1.2e-62;coverage=80.7;probability=0.92
TTGCGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGA
GTTTAAATCTCCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGTTACCAAT
TTAAAATGGCTGCATATATCCGGTTGGATGTAGAGGCCGGGTAAAAAAATACCCTTCTCT
AAAAA
>RST-Osativa-Cluster_7#SINE#F524|SINE RST-Osativa-Cluster_7#SINE/unknown|F524 ID=RST-Osativa-Cluster_7#SINE/unknown|F524;gene=F524;clade=SINE;evalue=3.7e-18;coverage=27.7;probability=0.86
TTGCGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGA
GTTTAAATCTCCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGTTACCAAT
TTAAAATGGCTGCATATATCCGGTTGG
>RST-Osativa-Cluster_7#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_7#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_7#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=1.5e-19;coverage=34.0;probability=0.75
GCGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TTAAATCTCCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGTTACCAATTT
AAAATGGCTGCATATATCCGGTTGGATGTAGAGGCCGGGTAAAAAAATACCCTTCTCTAA
AA
>RST-Osativa-Cluster_7#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_7#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_7#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=4e-09;coverage=29.0;probability=0.79
GCGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TTAAATCTCCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGTTACCAATTT
AAAATGGC
>RST-Osativa-Cluster_7#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_7#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_7#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=9.8e-19;coverage=27.6;probability=0.87
GGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTTAAAT
CTCCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGTTACCAATTTAAAATG
GCTGCATATATCCGGTTGGATGTAGAGGCCGGGTAAAAAAATACCCTTCTCTAAAAA
>RST-Osativa-Cluster_7#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_7#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_7#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=8.9e-15;coverage=24.1;probability=0.86
GCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTTAAATCT
CCATAGGAGCGAATTTCAGATTAGGTTATTTGAGGGGCTAAGT
>RST-Osativa-Cluster_7#SINE#CASINE|SINE RST-Osativa-Cluster_7#SINE/unknown|CASINE ID=RST-Osativa-Cluster_7#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=1.7e-46;coverage=90.3;probability=0.96
GTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTTAAATCTCCATAGGAGCGAATT
TCAGATTAGGTTATTTGAGGGGCTAAGTTACCAATTTAAAATGGCTGCATATATCCGGTT
GGATGTAGAGGCCGGGTAAAAAAATACCCTTCTCTAAAAA
>RST-Osativa-Cluster_8#SINE#OsSN3|SINE RST-Osativa-Cluster_8#SINE/unknown|OsSN3 ID=RST-Osativa-Cluster_8#SINE/unknown|OsSN3;gene=OsSN3;clade=SINE;evalue=2.6e-50;coverage=79.4;probability=0.93
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGT
AGAGGCCGGGTAAAAAATACCCTTCTCTAAA
>RST-Osativa-Cluster_8#SINE#F524|SINE RST-Osativa-Cluster_8#SINE/unknown|F524 ID=RST-Osativa-Cluster_8#SINE/unknown|F524;gene=F524;clade=SINE;evalue=5.1e-19;coverage=29.9;probability=0.84
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGT
AGAGGC
>RST-Osativa-Cluster_8#SINE#SINE2-1a_SBi|SINE RST-Osativa-Cluster_8#SINE/unknown|SINE2-1a_SBi ID=RST-Osativa-Cluster_8#SINE/unknown|SINE2-1a_SBi;gene=SINE2-1a_SBi;clade=SINE;evalue=1.3e-18;coverage=38.7;probability=0.82
GTGAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGT
TCAAATCTCCATAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGT
AGAGGCCGGGTAAAAAATACCCTTCTCTAA
>RST-Osativa-Cluster_8#SINE#SINE2-1c_SBi|SINE RST-Osativa-Cluster_8#SINE/unknown|SINE2-1c_SBi ID=RST-Osativa-Cluster_8#SINE/unknown|SINE2-1c_SBi;gene=SINE2-1c_SBi;clade=SINE;evalue=1.7e-08;coverage=27.7;probability=0.66
GAAAGGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTC
AAATCTCCATAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGTAG
AGGCCGGGTAAAAAATACCCTTCTCTA
>RST-Osativa-Cluster_8#SINE#SINE2-12_OS|SINE RST-Osativa-Cluster_8#SINE/unknown|SINE2-12_OS ID=RST-Osativa-Cluster_8#SINE/unknown|SINE2-12_OS;gene=SINE2-12_OS;clade=SINE;evalue=4.9e-19;coverage=30.0;probability=0.78
GGGCATGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAAT
CTCCATAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGTAGAGGC
CGGGTAAAAAATACCCTTCTCTAAA
>RST-Osativa-Cluster_8#SINE#SINE2-1_SBi|SINE RST-Osativa-Cluster_8#SINE/unknown|SINE2-1_SBi ID=RST-Osativa-Cluster_8#SINE/unknown|SINE2-1_SBi;gene=SINE2-1_SBi;clade=SINE;evalue=1.1e-13;coverage=24.1;probability=0.84
TGTAGCCTAGTGGTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAATCTCCA
TAGGAGCGAATTTCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGTAGAGGCCGGGT
AAAAAATACCCTTCTCTAA
>RST-Osativa-Cluster_8#SINE#CASINE|SINE RST-Osativa-Cluster_8#SINE/unknown|CASINE ID=RST-Osativa-Cluster_8#SINE/unknown|CASINE;gene=CASINE;clade=SINE;evalue=5.3e-32;coverage=89.1;probability=0.94
GTTGCAGTGACCTGAGTAGCACCCCAAGGTCCTGAGTTCAAATCTCCATAGGAGCGAATT
TCAGTGTTTTAAAGGCTGCATATATCCGGTTGGATGTAGAGGCCGGGTAAAAAATACCCT
TCTCTAAA
>RST-Osativa-Cluster_9#SINE#SINE2-1_OS|SINE RST-Osativa-Cluster_9#SINE/unknown|SINE2-1_OS ID=RST-Osativa-Cluster_9#SINE/unknown|SINE2-1_OS;gene=SINE2-1_OS;clade=SINE;evalue=8e-06;coverage=25.4;probability=0.74
CGCTAGTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCT
TGTCGAGCACGCTCACCAGGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACTCCA
AGTCCTTCTTTGGTGT
>RST-Osativa-Cluster_9#SINE#SINE2-3_OS|SINE RST-Osativa-Cluster_9#SINE/unknown|SINE2-3_OS ID=RST-Osativa-Cluster_9#SINE/unknown|SINE2-3_OS;gene=SINE2-3_OS;clade=SINE;evalue=3e-05;coverage=70.9;probability=0.7
AGTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCTTGTC
GAGCACGCTCACCAGGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACTCCAAGTC
CTTCTTTG
>RST-Osativa-Cluster_9#SINE#SINE2-2_OS|SINE RST-Osativa-Cluster_9#SINE/unknown|SINE2-2_OS ID=RST-Osativa-Cluster_9#SINE/unknown|SINE2-2_OS;gene=SINE2-2_OS;clade=SINE;evalue=1.5e-07;coverage=27.0;probability=0.74
GTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCTTGTCG
AGCACGCTCACCAGGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACTCC
>RST-Osativa-Cluster_9#SINE#SINE2-4_OS|SINE RST-Osativa-Cluster_9#SINE/unknown|SINE2-4_OS ID=RST-Osativa-Cluster_9#SINE/unknown|SINE2-4_OS;gene=SINE2-4_OS;clade=SINE;evalue=0.00061;coverage=64.3;probability=0.58
GTAGCGCAGTGGCAGGGGTCGCTGGCATGCACCCCGCCGGCCCGGGTTCGACCCTTGTCG
AGCACGCTCACCAGGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACTCCAAGTCC
TTCTTT
>RST-Osativa-Cluster_9#SINE#SINE2-4B_OS|SINE RST-Osativa-Cluster_9#SINE/unknown|SINE2-4B_OS ID=RST-Osativa-Cluster_9#SINE/unknown|SINE2-4B_OS;gene=SINE2-4B_OS;clade=SINE;evalue=0.00042;coverage=32.1;probability=0.76
CAGGGGAAATATTTACCTCTTCCTTCTTAAAACCATTGACTCCAAGTCCTTCTTTGGTGT
CCAACCTT
